# Site settings
name: RexK
title: RexK's Blog
email: myungsunrex@gmail.com
description: "Programming Discipline"
baseurl: ""
url: "http://rexk.github.io"
google_analytics_id: UA-52356838-1

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /posts/:title
relative_permalinks: false
exclude:
  - google-key.p12
